export const THEME_TOGGLE = "THEME_TOGGLE";
export const FONT_TOGGLE = "FONT_TOGGLE";
export const MENU_NUMBER_CHANGE = "MENU_NUMBER_CHANGE";
export const ON_TOGGLE_CONTENT = "ON_TOGGLE_CONTENT";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CONTENT_INFORMATION_NUMBER = "CONTENT_INFORMATION_NUMBER";
export const LAYOUT_NUMBER_CHANGE = "LAYOUT_NUMBER_CHANGE";
